image: docker:latest

services:
    - docker:dind
variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
    - build
    - test
    - deploy
before_script:
    - apk add sudo
    - sudo docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
build:
    stage: build
    script:
        - export DOCKER_HOST
        - sudo docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - sudo docker push "$CI_REGISTRY_IMAGE"
test:
    stage: test
    script:
        - sudo docker-compose run web python manage.py test 
deploy:
    stage: deploy
    script:
        - sudo apt -y install docker-compose
        - sudo docker-compose up 
    
