image: docker:latest

services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375


stages:
    - build
    - test
    - deploy
before_script:
    - apk update && apk add sudo
    - export DOCKER_HOST=tcp://localhost:2375
    - sudo docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 
build:
    stage: build
    script:
        - export DOCKER_HOST=tcp://localhost:2375
        - sudo docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - sudo docker push "$CI_REGISTRY_IMAGE"
test:
    stage: test
    script:
        - export DOCKER_HOST=tcp://localhost:2375
        - sudo docker-compose run web python manage.py test 
deploy:
    stage: deploy
    script:
        - export DOCKER_HOST=tcp://localhost:2375
        - sudo apt -y install docker-compose
        - sudo docker-compose up 
    