image: alpine:latest

variables:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: testing-password
  POSTGRES_ENABLED: "true"
  POSTGRES_DB: $CI_ENVIRONMENT_SLUG
  POSTGRES_VERSION: 9.6.2

  DOCKER_DRIVER: overlay2
  ROLLOUT_RESOURCE_TYPE: deployment
  DOCKER_TLS_CERTDIR: "" # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

stages:
    - build
    - test
    - deploy
before_script:
    - apk update && apk add sudo
    - export DOCKER_HOST=tcp://localhost:2375
    - rc-update add docker boot
    - service docker start
    - sudo docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 
build:
    stage: build
    script:
        - export DOCKER_HOST=tcp://localhost:2375
        - sudo docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - sudo docker push "$CI_REGISTRY_IMAGE"
test:
    stage: test
    script:
        - export DOCKER_HOST=tcp://localhost:2375
        - sudo docker-compose run web python manage.py test 
deploy:
    stage: deploy
    script:
        - export DOCKER_HOST=tcp://localhost:2375
        - sudo apt -y install docker-compose
        - sudo docker-compose up 
    